name: Docker Image CI

on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build -d

      - name: Verify
        run: |
          TRIGGER_EXECUTION_TIMESTAMP=$(docker-compose run airflow-worker airflow dags trigger Employee_Data_Loader | grep -oP '(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{6})?(?:[+-]\d{2}:\d{2}))' | head -n1)
          echo "Trigger Execution timestamp = $TRIGGER_EXECUTION_TIMESTAMP"
          docker-compose run airflow-worker airflow dags unpause Employee_Data_Loader
          sleep 30
          docker-compose run airflow-worker airflow dags state Employee_Data_Loader ${{ env.TRIGGER_EXECUTION_TIMESTAMP }}

      - name: Destroy
        run: |
          docker-compose down --volumes --remove-orphans
